name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install htslib
      run: sudo apt-get install libhts-dev
    - name: make
      run: make -C consecutive_kmers/cpp_code
    - name: make test
      run: make -C consecutive_kmers/cpp_code test
