name: Release Singularity Container on tag v*

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install htslib
      run: sudo apt-get install libhts-dev

    - name: Install SeqAn
      run: sudo apt-get install libseqan2-dev

    - name: Build C++ Project and Run Tests
      run: |
        make -C consecutive_kmers/cpp_code
        ./consecutive_kmers/cpp_code/bin/test

    - name: Install GO
      run: |
        wget https://go.dev/dl/go1.22.3.linux-arm64.tar.gz
        sudo tar -C /usr/local -xzvf go1.22.3.linux-arm64.tar.gz
        echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
        echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && \
        source ~/.bashrc

    - name: Install Singularity Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        autoconf \
        automake \
        cryptsetup \
        git \
        libfuse-dev \
        libglib2.0-dev \
        libseccomp-dev \
        libtool \
        pkg-config \
        runc \
        squashfs-tools \
        squashfs-tools-ng \
        uidmap \
        wget \
        zlib1g-dev

    - name: Install Singularity
      run: |
        git clone --recurse-submodules https://github.com/sylabs/singularity.git
        cd singularity
        git checkout --recurse-submodules v4.1.2
        ./mconfig
        make -C builddir
        sudo make -C builddir install

    - name: Build Singularity Container
      run: |
        singularity version
        sudo singularity build consecutive_kmers.sif .github/workflows/singularity.def

    - name: Test Singularity Container
      run: |
        singularity exec consecutive_kmers.sif test

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # add this in GitHub Secrets of the repository
        token: ${{ secrets.TOKEN }}
        # if not provided: Skip retry — your GitHub token/PAT does not have the required permission to create a release. Error: Resource not accessible by integration
        files: |
          consecutive_kmers.sif